server:
  host: "localhost"
  port: 9019

vosk:
  server_url: "ws://localhost:2700"
  sample_rate: 8000

transcription:
  provider: "assemblyai"
  output_dir: "./transcripts"
  save_transcripts: true
  save_audio: true

assemblyai:
  api_key: "590fa22d4e11403fa681db14eac44042"
  sample_rate: 8000